package iwpoo.alliance.model;

public class AllianceHotArticle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alliance_hot_article.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alliance_hot_article.media_id
     *
     * @mbggenerated
     */
    private Integer mediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alliance_hot_article.hot_article_name
     *
     * @mbggenerated
     */
    private String hotArticleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alliance_hot_article.exposure_num
     *
     * @mbggenerated
     */
    private Integer exposureNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alliance_hot_article.read_num
     *
     * @mbggenerated
     */
    private Integer readNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alliance_hot_article.hot_article_link
     *
     * @mbggenerated
     */
    private String hotArticleLink;

    public AllianceHotArticle(Integer id, Integer mediaId, String hotArticleName, Integer exposureNum, Integer readNum, String hotArticleLink) {
        this.id = id;
        this.mediaId = mediaId;
        this.hotArticleName = hotArticleName;
        this.exposureNum = exposureNum;
        this.readNum = readNum;
        this.hotArticleLink = hotArticleLink;
    }

    public AllianceHotArticle() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alliance_hot_article.id
     *
     * @return the value of alliance_hot_article.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alliance_hot_article.id
     *
     * @param id the value for alliance_hot_article.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alliance_hot_article.media_id
     *
     * @return the value of alliance_hot_article.media_id
     *
     * @mbggenerated
     */
    public Integer getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alliance_hot_article.media_id
     *
     * @param mediaId the value for alliance_hot_article.media_id
     *
     * @mbggenerated
     */
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alliance_hot_article.hot_article_name
     *
     * @return the value of alliance_hot_article.hot_article_name
     *
     * @mbggenerated
     */
    public String getHotArticleName() {
        return hotArticleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alliance_hot_article.hot_article_name
     *
     * @param hotArticleName the value for alliance_hot_article.hot_article_name
     *
     * @mbggenerated
     */
    public void setHotArticleName(String hotArticleName) {
        this.hotArticleName = hotArticleName == null ? null : hotArticleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alliance_hot_article.exposure_num
     *
     * @return the value of alliance_hot_article.exposure_num
     *
     * @mbggenerated
     */
    public Integer getExposureNum() {
        return exposureNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alliance_hot_article.exposure_num
     *
     * @param exposureNum the value for alliance_hot_article.exposure_num
     *
     * @mbggenerated
     */
    public void setExposureNum(Integer exposureNum) {
        this.exposureNum = exposureNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alliance_hot_article.read_num
     *
     * @return the value of alliance_hot_article.read_num
     *
     * @mbggenerated
     */
    public Integer getReadNum() {
        return readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alliance_hot_article.read_num
     *
     * @param readNum the value for alliance_hot_article.read_num
     *
     * @mbggenerated
     */
    public void setReadNum(Integer readNum) {
        this.readNum = readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alliance_hot_article.hot_article_link
     *
     * @return the value of alliance_hot_article.hot_article_link
     *
     * @mbggenerated
     */
    public String getHotArticleLink() {
        return hotArticleLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alliance_hot_article.hot_article_link
     *
     * @param hotArticleLink the value for alliance_hot_article.hot_article_link
     *
     * @mbggenerated
     */
    public void setHotArticleLink(String hotArticleLink) {
        this.hotArticleLink = hotArticleLink == null ? null : hotArticleLink.trim();
    }
}