package iwpoo.alliance.model;

import java.util.Date;

public class AlliancePicture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alliance_picture.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alliance_picture.media_id
     *
     * @mbggenerated
     */
    private Integer mediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alliance_picture.picture_url
     *
     * @mbggenerated
     */
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alliance_picture.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alliance_picture.weight
     *
     * @mbggenerated
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alliance_picture.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alliance_picture.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alliance_picture.status
     *
     * @mbggenerated
     */
    private Integer status;

    public AlliancePicture(Integer id, Integer mediaId, String pictureUrl, String description, Integer weight, Date createTime, Date updateTime, Integer status) {
        this.id = id;
        this.mediaId = mediaId;
        this.pictureUrl = pictureUrl;
        this.description = description;
        this.weight = weight;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.status = status;
    }

    public AlliancePicture() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alliance_picture.id
     *
     * @return the value of alliance_picture.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alliance_picture.id
     *
     * @param id the value for alliance_picture.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alliance_picture.media_id
     *
     * @return the value of alliance_picture.media_id
     *
     * @mbggenerated
     */
    public Integer getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alliance_picture.media_id
     *
     * @param mediaId the value for alliance_picture.media_id
     *
     * @mbggenerated
     */
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alliance_picture.picture_url
     *
     * @return the value of alliance_picture.picture_url
     *
     * @mbggenerated
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alliance_picture.picture_url
     *
     * @param pictureUrl the value for alliance_picture.picture_url
     *
     * @mbggenerated
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alliance_picture.description
     *
     * @return the value of alliance_picture.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alliance_picture.description
     *
     * @param description the value for alliance_picture.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alliance_picture.weight
     *
     * @return the value of alliance_picture.weight
     *
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alliance_picture.weight
     *
     * @param weight the value for alliance_picture.weight
     *
     * @mbggenerated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alliance_picture.create_time
     *
     * @return the value of alliance_picture.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alliance_picture.create_time
     *
     * @param createTime the value for alliance_picture.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alliance_picture.update_time
     *
     * @return the value of alliance_picture.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alliance_picture.update_time
     *
     * @param updateTime the value for alliance_picture.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alliance_picture.status
     *
     * @return the value of alliance_picture.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alliance_picture.status
     *
     * @param status the value for alliance_picture.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}