package iwpoo.alliance.model;

import java.util.ArrayList;
import java.util.List;

public class MediaExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table media
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table media
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table media
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media
	 * @mbggenerated
	 */
	public MediaExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table media
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table media
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMediaIdIsNull() {
			addCriterion("media_id is null");
			return (Criteria) this;
		}

		public Criteria andMediaIdIsNotNull() {
			addCriterion("media_id is not null");
			return (Criteria) this;
		}

		public Criteria andMediaIdEqualTo(Integer value) {
			addCriterion("media_id =", value, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdNotEqualTo(Integer value) {
			addCriterion("media_id <>", value, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdGreaterThan(Integer value) {
			addCriterion("media_id >", value, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("media_id >=", value, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdLessThan(Integer value) {
			addCriterion("media_id <", value, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdLessThanOrEqualTo(Integer value) {
			addCriterion("media_id <=", value, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdIn(List<Integer> values) {
			addCriterion("media_id in", values, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdNotIn(List<Integer> values) {
			addCriterion("media_id not in", values, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdBetween(Integer value1, Integer value2) {
			addCriterion("media_id between", value1, value2, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdNotBetween(Integer value1, Integer value2) {
			addCriterion("media_id not between", value1, value2, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaNameIsNull() {
			addCriterion("media_name is null");
			return (Criteria) this;
		}

		public Criteria andMediaNameIsNotNull() {
			addCriterion("media_name is not null");
			return (Criteria) this;
		}

		public Criteria andMediaNameEqualTo(String value) {
			addCriterion("media_name =", value, "mediaName");
			return (Criteria) this;
		}

		public Criteria andMediaNameNotEqualTo(String value) {
			addCriterion("media_name <>", value, "mediaName");
			return (Criteria) this;
		}

		public Criteria andMediaNameGreaterThan(String value) {
			addCriterion("media_name >", value, "mediaName");
			return (Criteria) this;
		}

		public Criteria andMediaNameGreaterThanOrEqualTo(String value) {
			addCriterion("media_name >=", value, "mediaName");
			return (Criteria) this;
		}

		public Criteria andMediaNameLessThan(String value) {
			addCriterion("media_name <", value, "mediaName");
			return (Criteria) this;
		}

		public Criteria andMediaNameLessThanOrEqualTo(String value) {
			addCriterion("media_name <=", value, "mediaName");
			return (Criteria) this;
		}

		public Criteria andMediaNameLike(String value) {
			addCriterion("media_name like", value, "mediaName");
			return (Criteria) this;
		}

		public Criteria andMediaNameNotLike(String value) {
			addCriterion("media_name not like", value, "mediaName");
			return (Criteria) this;
		}

		public Criteria andMediaNameIn(List<String> values) {
			addCriterion("media_name in", values, "mediaName");
			return (Criteria) this;
		}

		public Criteria andMediaNameNotIn(List<String> values) {
			addCriterion("media_name not in", values, "mediaName");
			return (Criteria) this;
		}

		public Criteria andMediaNameBetween(String value1, String value2) {
			addCriterion("media_name between", value1, value2, "mediaName");
			return (Criteria) this;
		}

		public Criteria andMediaNameNotBetween(String value1, String value2) {
			addCriterion("media_name not between", value1, value2, "mediaName");
			return (Criteria) this;
		}

		public Criteria andMediaPortraitIsNull() {
			addCriterion("media_portrait is null");
			return (Criteria) this;
		}

		public Criteria andMediaPortraitIsNotNull() {
			addCriterion("media_portrait is not null");
			return (Criteria) this;
		}

		public Criteria andMediaPortraitEqualTo(String value) {
			addCriterion("media_portrait =", value, "mediaPortrait");
			return (Criteria) this;
		}

		public Criteria andMediaPortraitNotEqualTo(String value) {
			addCriterion("media_portrait <>", value, "mediaPortrait");
			return (Criteria) this;
		}

		public Criteria andMediaPortraitGreaterThan(String value) {
			addCriterion("media_portrait >", value, "mediaPortrait");
			return (Criteria) this;
		}

		public Criteria andMediaPortraitGreaterThanOrEqualTo(String value) {
			addCriterion("media_portrait >=", value, "mediaPortrait");
			return (Criteria) this;
		}

		public Criteria andMediaPortraitLessThan(String value) {
			addCriterion("media_portrait <", value, "mediaPortrait");
			return (Criteria) this;
		}

		public Criteria andMediaPortraitLessThanOrEqualTo(String value) {
			addCriterion("media_portrait <=", value, "mediaPortrait");
			return (Criteria) this;
		}

		public Criteria andMediaPortraitLike(String value) {
			addCriterion("media_portrait like", value, "mediaPortrait");
			return (Criteria) this;
		}

		public Criteria andMediaPortraitNotLike(String value) {
			addCriterion("media_portrait not like", value, "mediaPortrait");
			return (Criteria) this;
		}

		public Criteria andMediaPortraitIn(List<String> values) {
			addCriterion("media_portrait in", values, "mediaPortrait");
			return (Criteria) this;
		}

		public Criteria andMediaPortraitNotIn(List<String> values) {
			addCriterion("media_portrait not in", values, "mediaPortrait");
			return (Criteria) this;
		}

		public Criteria andMediaPortraitBetween(String value1, String value2) {
			addCriterion("media_portrait between", value1, value2,
					"mediaPortrait");
			return (Criteria) this;
		}

		public Criteria andMediaPortraitNotBetween(String value1, String value2) {
			addCriterion("media_portrait not between", value1, value2,
					"mediaPortrait");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andIdentityCardIsNull() {
			addCriterion("identity_card is null");
			return (Criteria) this;
		}

		public Criteria andIdentityCardIsNotNull() {
			addCriterion("identity_card is not null");
			return (Criteria) this;
		}

		public Criteria andIdentityCardEqualTo(String value) {
			addCriterion("identity_card =", value, "identityCard");
			return (Criteria) this;
		}

		public Criteria andIdentityCardNotEqualTo(String value) {
			addCriterion("identity_card <>", value, "identityCard");
			return (Criteria) this;
		}

		public Criteria andIdentityCardGreaterThan(String value) {
			addCriterion("identity_card >", value, "identityCard");
			return (Criteria) this;
		}

		public Criteria andIdentityCardGreaterThanOrEqualTo(String value) {
			addCriterion("identity_card >=", value, "identityCard");
			return (Criteria) this;
		}

		public Criteria andIdentityCardLessThan(String value) {
			addCriterion("identity_card <", value, "identityCard");
			return (Criteria) this;
		}

		public Criteria andIdentityCardLessThanOrEqualTo(String value) {
			addCriterion("identity_card <=", value, "identityCard");
			return (Criteria) this;
		}

		public Criteria andIdentityCardLike(String value) {
			addCriterion("identity_card like", value, "identityCard");
			return (Criteria) this;
		}

		public Criteria andIdentityCardNotLike(String value) {
			addCriterion("identity_card not like", value, "identityCard");
			return (Criteria) this;
		}

		public Criteria andIdentityCardIn(List<String> values) {
			addCriterion("identity_card in", values, "identityCard");
			return (Criteria) this;
		}

		public Criteria andIdentityCardNotIn(List<String> values) {
			addCriterion("identity_card not in", values, "identityCard");
			return (Criteria) this;
		}

		public Criteria andIdentityCardBetween(String value1, String value2) {
			addCriterion("identity_card between", value1, value2,
					"identityCard");
			return (Criteria) this;
		}

		public Criteria andIdentityCardNotBetween(String value1, String value2) {
			addCriterion("identity_card not between", value1, value2,
					"identityCard");
			return (Criteria) this;
		}

		public Criteria andWeixinPubilcIsNull() {
			addCriterion("weixin_pubilc is null");
			return (Criteria) this;
		}

		public Criteria andWeixinPubilcIsNotNull() {
			addCriterion("weixin_pubilc is not null");
			return (Criteria) this;
		}

		public Criteria andWeixinPubilcEqualTo(String value) {
			addCriterion("weixin_pubilc =", value, "weixinPubilc");
			return (Criteria) this;
		}

		public Criteria andWeixinPubilcNotEqualTo(String value) {
			addCriterion("weixin_pubilc <>", value, "weixinPubilc");
			return (Criteria) this;
		}

		public Criteria andWeixinPubilcGreaterThan(String value) {
			addCriterion("weixin_pubilc >", value, "weixinPubilc");
			return (Criteria) this;
		}

		public Criteria andWeixinPubilcGreaterThanOrEqualTo(String value) {
			addCriterion("weixin_pubilc >=", value, "weixinPubilc");
			return (Criteria) this;
		}

		public Criteria andWeixinPubilcLessThan(String value) {
			addCriterion("weixin_pubilc <", value, "weixinPubilc");
			return (Criteria) this;
		}

		public Criteria andWeixinPubilcLessThanOrEqualTo(String value) {
			addCriterion("weixin_pubilc <=", value, "weixinPubilc");
			return (Criteria) this;
		}

		public Criteria andWeixinPubilcLike(String value) {
			addCriterion("weixin_pubilc like", value, "weixinPubilc");
			return (Criteria) this;
		}

		public Criteria andWeixinPubilcNotLike(String value) {
			addCriterion("weixin_pubilc not like", value, "weixinPubilc");
			return (Criteria) this;
		}

		public Criteria andWeixinPubilcIn(List<String> values) {
			addCriterion("weixin_pubilc in", values, "weixinPubilc");
			return (Criteria) this;
		}

		public Criteria andWeixinPubilcNotIn(List<String> values) {
			addCriterion("weixin_pubilc not in", values, "weixinPubilc");
			return (Criteria) this;
		}

		public Criteria andWeixinPubilcBetween(String value1, String value2) {
			addCriterion("weixin_pubilc between", value1, value2,
					"weixinPubilc");
			return (Criteria) this;
		}

		public Criteria andWeixinPubilcNotBetween(String value1, String value2) {
			addCriterion("weixin_pubilc not between", value1, value2,
					"weixinPubilc");
			return (Criteria) this;
		}

		public Criteria andContactsIsNull() {
			addCriterion("contacts is null");
			return (Criteria) this;
		}

		public Criteria andContactsIsNotNull() {
			addCriterion("contacts is not null");
			return (Criteria) this;
		}

		public Criteria andContactsEqualTo(String value) {
			addCriterion("contacts =", value, "contacts");
			return (Criteria) this;
		}

		public Criteria andContactsNotEqualTo(String value) {
			addCriterion("contacts <>", value, "contacts");
			return (Criteria) this;
		}

		public Criteria andContactsGreaterThan(String value) {
			addCriterion("contacts >", value, "contacts");
			return (Criteria) this;
		}

		public Criteria andContactsGreaterThanOrEqualTo(String value) {
			addCriterion("contacts >=", value, "contacts");
			return (Criteria) this;
		}

		public Criteria andContactsLessThan(String value) {
			addCriterion("contacts <", value, "contacts");
			return (Criteria) this;
		}

		public Criteria andContactsLessThanOrEqualTo(String value) {
			addCriterion("contacts <=", value, "contacts");
			return (Criteria) this;
		}

		public Criteria andContactsLike(String value) {
			addCriterion("contacts like", value, "contacts");
			return (Criteria) this;
		}

		public Criteria andContactsNotLike(String value) {
			addCriterion("contacts not like", value, "contacts");
			return (Criteria) this;
		}

		public Criteria andContactsIn(List<String> values) {
			addCriterion("contacts in", values, "contacts");
			return (Criteria) this;
		}

		public Criteria andContactsNotIn(List<String> values) {
			addCriterion("contacts not in", values, "contacts");
			return (Criteria) this;
		}

		public Criteria andContactsBetween(String value1, String value2) {
			addCriterion("contacts between", value1, value2, "contacts");
			return (Criteria) this;
		}

		public Criteria andContactsNotBetween(String value1, String value2) {
			addCriterion("contacts not between", value1, value2, "contacts");
			return (Criteria) this;
		}

		public Criteria andContactsMailIsNull() {
			addCriterion("contacts_mail is null");
			return (Criteria) this;
		}

		public Criteria andContactsMailIsNotNull() {
			addCriterion("contacts_mail is not null");
			return (Criteria) this;
		}

		public Criteria andContactsMailEqualTo(String value) {
			addCriterion("contacts_mail =", value, "contactsMail");
			return (Criteria) this;
		}

		public Criteria andContactsMailNotEqualTo(String value) {
			addCriterion("contacts_mail <>", value, "contactsMail");
			return (Criteria) this;
		}

		public Criteria andContactsMailGreaterThan(String value) {
			addCriterion("contacts_mail >", value, "contactsMail");
			return (Criteria) this;
		}

		public Criteria andContactsMailGreaterThanOrEqualTo(String value) {
			addCriterion("contacts_mail >=", value, "contactsMail");
			return (Criteria) this;
		}

		public Criteria andContactsMailLessThan(String value) {
			addCriterion("contacts_mail <", value, "contactsMail");
			return (Criteria) this;
		}

		public Criteria andContactsMailLessThanOrEqualTo(String value) {
			addCriterion("contacts_mail <=", value, "contactsMail");
			return (Criteria) this;
		}

		public Criteria andContactsMailLike(String value) {
			addCriterion("contacts_mail like", value, "contactsMail");
			return (Criteria) this;
		}

		public Criteria andContactsMailNotLike(String value) {
			addCriterion("contacts_mail not like", value, "contactsMail");
			return (Criteria) this;
		}

		public Criteria andContactsMailIn(List<String> values) {
			addCriterion("contacts_mail in", values, "contactsMail");
			return (Criteria) this;
		}

		public Criteria andContactsMailNotIn(List<String> values) {
			addCriterion("contacts_mail not in", values, "contactsMail");
			return (Criteria) this;
		}

		public Criteria andContactsMailBetween(String value1, String value2) {
			addCriterion("contacts_mail between", value1, value2,
					"contactsMail");
			return (Criteria) this;
		}

		public Criteria andContactsMailNotBetween(String value1, String value2) {
			addCriterion("contacts_mail not between", value1, value2,
					"contactsMail");
			return (Criteria) this;
		}

		public Criteria andContactsWeixinIsNull() {
			addCriterion("contacts_weixin is null");
			return (Criteria) this;
		}

		public Criteria andContactsWeixinIsNotNull() {
			addCriterion("contacts_weixin is not null");
			return (Criteria) this;
		}

		public Criteria andContactsWeixinEqualTo(String value) {
			addCriterion("contacts_weixin =", value, "contactsWeixin");
			return (Criteria) this;
		}

		public Criteria andContactsWeixinNotEqualTo(String value) {
			addCriterion("contacts_weixin <>", value, "contactsWeixin");
			return (Criteria) this;
		}

		public Criteria andContactsWeixinGreaterThan(String value) {
			addCriterion("contacts_weixin >", value, "contactsWeixin");
			return (Criteria) this;
		}

		public Criteria andContactsWeixinGreaterThanOrEqualTo(String value) {
			addCriterion("contacts_weixin >=", value, "contactsWeixin");
			return (Criteria) this;
		}

		public Criteria andContactsWeixinLessThan(String value) {
			addCriterion("contacts_weixin <", value, "contactsWeixin");
			return (Criteria) this;
		}

		public Criteria andContactsWeixinLessThanOrEqualTo(String value) {
			addCriterion("contacts_weixin <=", value, "contactsWeixin");
			return (Criteria) this;
		}

		public Criteria andContactsWeixinLike(String value) {
			addCriterion("contacts_weixin like", value, "contactsWeixin");
			return (Criteria) this;
		}

		public Criteria andContactsWeixinNotLike(String value) {
			addCriterion("contacts_weixin not like", value, "contactsWeixin");
			return (Criteria) this;
		}

		public Criteria andContactsWeixinIn(List<String> values) {
			addCriterion("contacts_weixin in", values, "contactsWeixin");
			return (Criteria) this;
		}

		public Criteria andContactsWeixinNotIn(List<String> values) {
			addCriterion("contacts_weixin not in", values, "contactsWeixin");
			return (Criteria) this;
		}

		public Criteria andContactsWeixinBetween(String value1, String value2) {
			addCriterion("contacts_weixin between", value1, value2,
					"contactsWeixin");
			return (Criteria) this;
		}

		public Criteria andContactsWeixinNotBetween(String value1, String value2) {
			addCriterion("contacts_weixin not between", value1, value2,
					"contactsWeixin");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andTwoDimensionCodeIsNull() {
			addCriterion("two_dimension_code is null");
			return (Criteria) this;
		}

		public Criteria andTwoDimensionCodeIsNotNull() {
			addCriterion("two_dimension_code is not null");
			return (Criteria) this;
		}

		public Criteria andTwoDimensionCodeEqualTo(String value) {
			addCriterion("two_dimension_code =", value, "twoDimensionCode");
			return (Criteria) this;
		}

		public Criteria andTwoDimensionCodeNotEqualTo(String value) {
			addCriterion("two_dimension_code <>", value, "twoDimensionCode");
			return (Criteria) this;
		}

		public Criteria andTwoDimensionCodeGreaterThan(String value) {
			addCriterion("two_dimension_code >", value, "twoDimensionCode");
			return (Criteria) this;
		}

		public Criteria andTwoDimensionCodeGreaterThanOrEqualTo(String value) {
			addCriterion("two_dimension_code >=", value, "twoDimensionCode");
			return (Criteria) this;
		}

		public Criteria andTwoDimensionCodeLessThan(String value) {
			addCriterion("two_dimension_code <", value, "twoDimensionCode");
			return (Criteria) this;
		}

		public Criteria andTwoDimensionCodeLessThanOrEqualTo(String value) {
			addCriterion("two_dimension_code <=", value, "twoDimensionCode");
			return (Criteria) this;
		}

		public Criteria andTwoDimensionCodeLike(String value) {
			addCriterion("two_dimension_code like", value, "twoDimensionCode");
			return (Criteria) this;
		}

		public Criteria andTwoDimensionCodeNotLike(String value) {
			addCriterion("two_dimension_code not like", value,
					"twoDimensionCode");
			return (Criteria) this;
		}

		public Criteria andTwoDimensionCodeIn(List<String> values) {
			addCriterion("two_dimension_code in", values, "twoDimensionCode");
			return (Criteria) this;
		}

		public Criteria andTwoDimensionCodeNotIn(List<String> values) {
			addCriterion("two_dimension_code not in", values,
					"twoDimensionCode");
			return (Criteria) this;
		}

		public Criteria andTwoDimensionCodeBetween(String value1, String value2) {
			addCriterion("two_dimension_code between", value1, value2,
					"twoDimensionCode");
			return (Criteria) this;
		}

		public Criteria andTwoDimensionCodeNotBetween(String value1,
				String value2) {
			addCriterion("two_dimension_code not between", value1, value2,
					"twoDimensionCode");
			return (Criteria) this;
		}

		public Criteria andWeightIsNull() {
			addCriterion("weight is null");
			return (Criteria) this;
		}

		public Criteria andWeightIsNotNull() {
			addCriterion("weight is not null");
			return (Criteria) this;
		}

		public Criteria andWeightEqualTo(Integer value) {
			addCriterion("weight =", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotEqualTo(Integer value) {
			addCriterion("weight <>", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightGreaterThan(Integer value) {
			addCriterion("weight >", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
			addCriterion("weight >=", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightLessThan(Integer value) {
			addCriterion("weight <", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightLessThanOrEqualTo(Integer value) {
			addCriterion("weight <=", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightIn(List<Integer> values) {
			addCriterion("weight in", values, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotIn(List<Integer> values) {
			addCriterion("weight not in", values, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightBetween(Integer value1, Integer value2) {
			addCriterion("weight between", value1, value2, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotBetween(Integer value1, Integer value2) {
			addCriterion("weight not between", value1, value2, "weight");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table media
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table media
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}