package iwpoo.alliance.model;

public class Media {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.media_id
     *
     * @mbggenerated
     */
    private Integer mediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.media_name
     *
     * @mbggenerated
     */
    private String mediaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.media_portrait
     *
     * @mbggenerated
     */
    private String mediaPortrait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.identity_card
     *
     * @mbggenerated
     */
    private String identityCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.weixin_pubilc
     *
     * @mbggenerated
     */
    private String weixinPubilc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.contacts
     *
     * @mbggenerated
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.contacts_mail
     *
     * @mbggenerated
     */
    private String contactsMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.contacts_weixin
     *
     * @mbggenerated
     */
    private String contactsWeixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.two_dimension_code
     *
     * @mbggenerated
     */
    private String twoDimensionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.weight
     *
     * @mbggenerated
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media.media_materials
     *
     * @mbggenerated
     */
    private String mediaMaterials;

    public Media(Integer mediaId, String mediaName, String mediaPortrait, String phone, String identityCard, String weixinPubilc, String contacts, String contactsMail, String contactsWeixin, Integer status, String twoDimensionCode, Integer weight, String mediaMaterials) {
        this.mediaId = mediaId;
        this.mediaName = mediaName;
        this.mediaPortrait = mediaPortrait;
        this.phone = phone;
        this.identityCard = identityCard;
        this.weixinPubilc = weixinPubilc;
        this.contacts = contacts;
        this.contactsMail = contactsMail;
        this.contactsWeixin = contactsWeixin;
        this.status = status;
        this.twoDimensionCode = twoDimensionCode;
        this.weight = weight;
        this.mediaMaterials = mediaMaterials;
    }

    public Media() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.media_id
     *
     * @return the value of media.media_id
     *
     * @mbggenerated
     */
    public Integer getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.media_id
     *
     * @param mediaId the value for media.media_id
     *
     * @mbggenerated
     */
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.media_name
     *
     * @return the value of media.media_name
     *
     * @mbggenerated
     */
    public String getMediaName() {
        return mediaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.media_name
     *
     * @param mediaName the value for media.media_name
     *
     * @mbggenerated
     */
    public void setMediaName(String mediaName) {
        this.mediaName = mediaName == null ? null : mediaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.media_portrait
     *
     * @return the value of media.media_portrait
     *
     * @mbggenerated
     */
    public String getMediaPortrait() {
        return mediaPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.media_portrait
     *
     * @param mediaPortrait the value for media.media_portrait
     *
     * @mbggenerated
     */
    public void setMediaPortrait(String mediaPortrait) {
        this.mediaPortrait = mediaPortrait == null ? null : mediaPortrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.phone
     *
     * @return the value of media.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.phone
     *
     * @param phone the value for media.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.identity_card
     *
     * @return the value of media.identity_card
     *
     * @mbggenerated
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.identity_card
     *
     * @param identityCard the value for media.identity_card
     *
     * @mbggenerated
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard == null ? null : identityCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.weixin_pubilc
     *
     * @return the value of media.weixin_pubilc
     *
     * @mbggenerated
     */
    public String getWeixinPubilc() {
        return weixinPubilc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.weixin_pubilc
     *
     * @param weixinPubilc the value for media.weixin_pubilc
     *
     * @mbggenerated
     */
    public void setWeixinPubilc(String weixinPubilc) {
        this.weixinPubilc = weixinPubilc == null ? null : weixinPubilc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.contacts
     *
     * @return the value of media.contacts
     *
     * @mbggenerated
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.contacts
     *
     * @param contacts the value for media.contacts
     *
     * @mbggenerated
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.contacts_mail
     *
     * @return the value of media.contacts_mail
     *
     * @mbggenerated
     */
    public String getContactsMail() {
        return contactsMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.contacts_mail
     *
     * @param contactsMail the value for media.contacts_mail
     *
     * @mbggenerated
     */
    public void setContactsMail(String contactsMail) {
        this.contactsMail = contactsMail == null ? null : contactsMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.contacts_weixin
     *
     * @return the value of media.contacts_weixin
     *
     * @mbggenerated
     */
    public String getContactsWeixin() {
        return contactsWeixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.contacts_weixin
     *
     * @param contactsWeixin the value for media.contacts_weixin
     *
     * @mbggenerated
     */
    public void setContactsWeixin(String contactsWeixin) {
        this.contactsWeixin = contactsWeixin == null ? null : contactsWeixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.status
     *
     * @return the value of media.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.status
     *
     * @param status the value for media.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.two_dimension_code
     *
     * @return the value of media.two_dimension_code
     *
     * @mbggenerated
     */
    public String getTwoDimensionCode() {
        return twoDimensionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.two_dimension_code
     *
     * @param twoDimensionCode the value for media.two_dimension_code
     *
     * @mbggenerated
     */
    public void setTwoDimensionCode(String twoDimensionCode) {
        this.twoDimensionCode = twoDimensionCode == null ? null : twoDimensionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.weight
     *
     * @return the value of media.weight
     *
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.weight
     *
     * @param weight the value for media.weight
     *
     * @mbggenerated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.media_materials
     *
     * @return the value of media.media_materials
     *
     * @mbggenerated
     */
    public String getMediaMaterials() {
        return mediaMaterials;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.media_materials
     *
     * @param mediaMaterials the value for media.media_materials
     *
     * @mbggenerated
     */
    public void setMediaMaterials(String mediaMaterials) {
        this.mediaMaterials = mediaMaterials == null ? null : mediaMaterials.trim();
    }
}