package iwpoo.alliance.model;

public class StatisticsMedia {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics_media.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics_media.media_id
     *
     * @mbggenerated
     */
    private Integer mediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics_media.read_num
     *
     * @mbggenerated
     */
    private Integer readNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics_media.new_read_num
     *
     * @mbggenerated
     */
    private Integer newReadNum;

    public StatisticsMedia(Integer id, Integer mediaId, Integer readNum, Integer newReadNum) {
        this.id = id;
        this.mediaId = mediaId;
        this.readNum = readNum;
        this.newReadNum = newReadNum;
    }

    public StatisticsMedia() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics_media.id
     *
     * @return the value of statistics_media.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics_media.id
     *
     * @param id the value for statistics_media.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics_media.media_id
     *
     * @return the value of statistics_media.media_id
     *
     * @mbggenerated
     */
    public Integer getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics_media.media_id
     *
     * @param mediaId the value for statistics_media.media_id
     *
     * @mbggenerated
     */
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics_media.read_num
     *
     * @return the value of statistics_media.read_num
     *
     * @mbggenerated
     */
    public Integer getReadNum() {
        return readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics_media.read_num
     *
     * @param readNum the value for statistics_media.read_num
     *
     * @mbggenerated
     */
    public void setReadNum(Integer readNum) {
        this.readNum = readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics_media.new_read_num
     *
     * @return the value of statistics_media.new_read_num
     *
     * @mbggenerated
     */
    public Integer getNewReadNum() {
        return newReadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics_media.new_read_num
     *
     * @param newReadNum the value for statistics_media.new_read_num
     *
     * @mbggenerated
     */
    public void setNewReadNum(Integer newReadNum) {
        this.newReadNum = newReadNum;
    }
}