package iwpoo.alliance.dao;

import iwpoo.alliance.model.AllianceHotArticle;
import iwpoo.alliance.model.AllianceHotArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllianceHotArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_hot_article
     *
     * @mbggenerated
     */
    int countByExample(AllianceHotArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_hot_article
     *
     * @mbggenerated
     */
    int deleteByExample(AllianceHotArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_hot_article
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_hot_article
     *
     * @mbggenerated
     */
    int insert(AllianceHotArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_hot_article
     *
     * @mbggenerated
     */
    int insertSelective(AllianceHotArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_hot_article
     *
     * @mbggenerated
     */
    List<AllianceHotArticle> selectByExample(AllianceHotArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_hot_article
     *
     * @mbggenerated
     */
    AllianceHotArticle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_hot_article
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AllianceHotArticle record, @Param("example") AllianceHotArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_hot_article
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AllianceHotArticle record, @Param("example") AllianceHotArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_hot_article
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AllianceHotArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_hot_article
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AllianceHotArticle record);
}