package iwpoo.alliance.dao;

import iwpoo.alliance.model.AlliancePicture;
import iwpoo.alliance.model.AlliancePictureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlliancePictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_picture
     *
     * @mbggenerated
     */
    int countByExample(AlliancePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_picture
     *
     * @mbggenerated
     */
    int deleteByExample(AlliancePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_picture
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_picture
     *
     * @mbggenerated
     */
    int insert(AlliancePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_picture
     *
     * @mbggenerated
     */
    int insertSelective(AlliancePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_picture
     *
     * @mbggenerated
     */
    List<AlliancePicture> selectByExample(AlliancePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_picture
     *
     * @mbggenerated
     */
    AlliancePicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_picture
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AlliancePicture record, @Param("example") AlliancePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_picture
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AlliancePicture record, @Param("example") AlliancePictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_picture
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AlliancePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_picture
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AlliancePicture record);
}