package iwpoo.alliance.dao;

import iwpoo.alliance.model.Media;
import iwpoo.alliance.model.MediaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MediaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated
     */
    int countByExample(MediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated
     */
    int deleteByExample(MediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mediaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated
     */
    int insert(Media record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated
     */
    int insertSelective(Media record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated
     */
    List<Media> selectByExampleWithBLOBs(MediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated
     */
    List<Media> selectByExample(MediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated
     */
    Media selectByPrimaryKey(Integer mediaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Media record, @Param("example") MediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Media record, @Param("example") MediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Media record, @Param("example") MediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Media record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Media record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Media record);
}