package iwpoo.alliance.dao;

import iwpoo.alliance.model.StatisticsMedia;
import iwpoo.alliance.model.StatisticsMediaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StatisticsMediaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_media
     *
     * @mbggenerated
     */
    int countByExample(StatisticsMediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_media
     *
     * @mbggenerated
     */
    int deleteByExample(StatisticsMediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_media
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_media
     *
     * @mbggenerated
     */
    int insert(StatisticsMedia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_media
     *
     * @mbggenerated
     */
    int insertSelective(StatisticsMedia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_media
     *
     * @mbggenerated
     */
    List<StatisticsMedia> selectByExample(StatisticsMediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_media
     *
     * @mbggenerated
     */
    StatisticsMedia selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_media
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StatisticsMedia record, @Param("example") StatisticsMediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_media
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StatisticsMedia record, @Param("example") StatisticsMediaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_media
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatisticsMedia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics_media
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatisticsMedia record);
}